development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: eartraining
  username: root
  password: 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: eartraining_test
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: eartraining
  username: root
  password:
